service: concert-search

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - "!./**"
    - ./dist/**
    - ./package.json

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: 
      allowedOrigins: 
        - "https://concert-search.com"
      allowedMethods:
        - GET
        - POST
      maxAge: 600

functions:
  main:
    handler: dist/main.handler
    timeout: 29
    events:
      - httpApi:
          method: POST
          path: '/concerts'
      - httpApi:
          method: GET
          path: '/concerts/{id}'