service: concert-search

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - "!./**"
    - ./dist/**
    - ./package.json

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/main.handler
    events:
      - httpApi:
          method: POST
          path: '/concerts'
      - httpApi:
          method: GET
          path: '/concerts/{id}'